name: Elsa 3 Custom Packages
on:
  workflow_dispatch:
  push:
    branches:
      - v3-custom-nuget
    tags:
      - preview-*hotfix-* # e.g. preview-1.0.0-hotfix-1
  release:
    types: [ prereleased ]
env:
  AZURE_ARTIFACTS_FEED_URL: ${{ secrets.AZURE_ARTIFACTS_FEED_URL}}
  feedz_feed_source: 'https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json'
  nuget_feed_source: 'https://api.nuget.org/v3/index.json'
  package_number_reference: ${{ vars.PACKAGE_NUMBER_REFERENCE }}
  
jobs:
  build:
    name: Build packages
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      
      
      - name: Verify commit exists in origin/v3-custom-package
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/v3
      - name: Set VERSION variable
        run:  |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME=${{ github.ref }} # e.g., refs/tags/preview-740-hotfix-1
            TAG_NAME=${TAG_NAME#refs/tags/} # remove the refs/tags/ prefix
            echo "VERSION=3.0.0-preview-${TAG_NAME}.${{github.run_number}}" >> $GITHUB_ENV
          else
            echo "VERSION=3.0.0-preview.${{env.package_number_reference}}.${{github.run_number}}" >> $GITHUB_ENV
          fi
      
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} /p:PackageOutputPath=$(pwd)/packages
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: elsa-nuget-packages
          path: packages/*nupkg
        if: ${{ github.event_name == 'release' || github.event_name == 'push'}}
        
  publish_custom_feed:
    name: Publish to custom feed
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event_name == 'release' || github.event_name == 'push'}}
    steps:
      - name: Download Packages
        uses: actions/download-artifact@v3
        with:
          name: elsa-nuget-packages
      
      - uses: actions/setup-dotnet@v3
        with:
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
      - name: Publish to custom feed
        run: dotnet nuget push *.nupkg --api-key AureArtifacts --skip-duplicate
